### ISSUE TITLE
Default value of active_control.velMax

### ISSUE THREAD

**Issue by olivecha** [AMReX-Combustion/PeleLMeX#232]
Upon adding active control to my simulation case, the inlet speed kept going to zero resulting in a flash-back. 

I found out by looking at `PeleLM.H` that `m_ctrl_velMax` is set to zero by default, resulting in `Vnew` always being equal to zero:
```cpp
225     Vnew = std::max(Vnew, 0.0);
227     Vnew = std::min(Vnew, m_ctrl_velMax);
```

I don't have an issue anymore with using active control as I know I can just supply a value to make my case work, but perhaps something should be changed either in the TripleFlame example:
```bash
active_control.velMax = 1.0               # Optional: limit inlet velocity
```
Or in the code by adding a condition for line 227 of `PeleLMFlowControler.cpp` (slow ?) or setting an arbitrary large default value in `PeleLM.H` (not good practice ?). 

I would be appy to submit a pull request with the corresponding changes.

**Comment by baperry2** [comment]
Good catch. As it stands, setting `active_control.velMax` is basically mandatory.

One solution would be to default `m_ctrl_velMax` to a negative number and then have a conditional to only apply the limit if the value of `m_ctrl_velMax` is positive (the control velocity must always be positive). No performance issue because this is not a pointwise operation. 

Please do submit a pull request!
