### ISSUE TITLE
Repository size is too large

### ISSUE THREAD

**Issue by esclapez** [AMReX-Combustion/PeleLMeX#307]
LMeX repo is close to 200MB, something is probably up, where large files have been commited.

**Comment by baperry2** [comment]
The repo size appears to be due to some turb inflow files in a few of the non-development branches. It appears that we have several branches dedicated to specific cases from specific users. I think that going forward we should not allow that - if someone has a specific case they are running, they should create a branch for that on their own fork, rather than here, so it doesn't bloat this repo unnecessarily. For the existing branches, we should see what can be cleaned up, moved to a fork, or deleted if stale.

**Comment by drummerdoc** [comment]
Agreed.  Can we get a list of offending setups/owners? I'm happy to help reach out politely to work with them.

**Comment by baperry2** [comment]
The big offenders were some SAF cases that I moved to their own repo, so now the size of LMeX is down to ~25 MB. 

There are still a few extraneous branches dedicated to case setup (it's fine to keep branches for new features here) from @bssoriano @esclapez and @nickwimer, these could be cleaned up but none of them have any super large files.

**Comment by drummerdoc** [comment]
> The big offenders were some SAF cases that I moved to their own repo, so now the size of LMeX is down to ~25 MB.
> 
> There are still a few extraneous branches dedicated to case setup (it's fine to keep branches for new features here) from @bssoriano @esclapez and @nickwimer, these could be cleaned up but none of them have any super large files.

Great.  Hope those 3 can clean things up a bit, as every little bit helps.  Thanks Bruce!

**Comment by baperry2** [comment]
@esclapez can we close this, or should that wait on cleaning up excess branches?
