### ISSUE TITLE
EB_FlamePastCylinder

### ISSUE THREAD

**Issue by czc-zju** [AMReX-Combustion/PeleLMeX#95]
@[esclapez](https://github.com/AMReX-Combustion/PeleLMeX/commits?author=esclapez) I made a case that EB_FlamePastCylinder in PeleLMeX (because I want to use the isothermal boundary of EB),  the calculation is very fast only flow, but adding the reaction, the calculation becomes very slow.  This is my input file：
                                           [input.txt](https://github.com/AMReX-Combustion/PeleLMeX/files/8838219/input.txt)

**Comment by czc-zju** [comment]
@[esclapez](https://github.com/AMReX-Combustion/PeleLMeX/commits?author=esclapez)  I really hope you can give me some advice

**Comment by esclapez** [comment]
I'm not surprised that the reactive simulation is slower than the non-reactive one, the chemistry integration is generally one of the most computationally expensive part. When you say slow, is it slower than what you had with a similar setup in PeleLM ?

**Comment by czc-zju** [comment]
@esclapez It is very slow and almost stops calculating in PeleLMeX, which is much slower than that in PeleLM.
These are my settings files:
[GNUmakefile.txt](https://github.com/AMReX-Combustion/PeleLMeX/files/8849175/GNUmakefile.txt)
[input.txt](https://github.com/AMReX-Combustion/PeleLMeX/files/8849176/input.txt)
[pelelm_prob_cpp.txt](https://github.com/AMReX-Combustion/PeleLMeX/files/8849177/pelelm_prob_cpp.txt)
[pelelm_prob_H.txt](https://github.com/AMReX-Combustion/PeleLMeX/files/8849178/pelelm_prob_H.txt)
[pelelm_prob_parm_H.txt](https://github.com/AMReX-Combustion/PeleLMeX/files/8849179/pelelm_prob_parm_H.txt)

**Comment by mameehan5** [comment]
I recently had a problem similar to this and found reinstalling (simple re-cloning) the Pele suite fixed the issue.

**Comment by czc-zju** [comment]
I reinstalled it but the problem wasn't resolved.
I installed its branch:
https://github.com/AMReX-Combustion/PeleLMeX/tree/isoT_EB

**Comment by esclapez** [comment]
I've add a look at your case and there are a couple of things:
 - you're using `Transport_Model = Constant`, but that'll just not work well to get a flame. You can switch to `Transport_Model = Simple`
 - a blocking factor of 4 will strongly limit the convergence of the linear solvers because they are based on GMG. I would recommend using 16, that enable a couple of of MG levels
 - the initial condition contains premixed CH4+air at 1800 K in the wake of the step. It creates an entire region of high reactivity, which might explains the slow down with reaction ON.

I have setup and run the case for a little while, getting the temperature field below. I've changed your setup a bit, with a domain and base grid:
```
geometry.prob_lo     = -0.01   -0.01        # x_lo y_lo (z_lo)
geometry.prob_hi     =  0.05    0.01        # x_hi y_hi (z_hi)
amr.n_cell                 = 192 64
```
and I used two levels of refinement. With this configuration, it takes about 0.9s per step using 32 MPI ranks. How does that compare to the timing you have ?

<img width="772" alt="Screen Shot 2022-06-06 at 11 31 44 PM" src="https://user-images.githubusercontent.com/13371051/172311494-79fda6da-fc70-4f5b-bfc2-03acc02c215c.png">

**Comment by esclapez** [comment]
This is a rather interesting (testing several aspects of the code) yet simple case, so I could add it to our RegTests and you can update from there.

**Comment by czc-zju** [comment]
Ok, that's great, I'll be waiting for your update.
Thank you!!!!!

**Comment by esclapez** [comment]
I've updated the
https://github.com/AMReX-Combustion/PeleLMeX/tree/isoT_EB
branch with an `RegTests/EB_BackwardStepFlame` case.

If you can give it a try and see how fast/slow it is ?

**Comment by czc-zju** [comment]
Thank you @esclapez and @Mike Meehan. I reinstalled it three times and the calculation became faster on the third time, it takes about 2s per step using 4 MPI ranks . 
I want to get the diffusion coefficient _"D("+spec_names[n]+"_, I added **diffTerm** to the input file, but the output plot file does't have D_ , what should I do?

**Comment by drummerdoc** [comment]
Why is there refinement on the inflow face at the step?

**Comment by esclapez** [comment]
@drummerdoc the refinement is based on gradT and initially I had the air temperature across the entire _x-_ face. Switched to the covered T value on the EB-covered part and the refinement is now removed.

@czc-zju I recently added the viscosity but not the diffusion coefficient. I'll add that too. Note that `diffTerm` is used to get the species/enthalpy diffusion terms when the code run in 'evaluate' mode, which is used for unit tests.

**Comment by esclapez** [comment]
@czc-zju @mameehan5 I'm not sure I understand the re-installing trick. I've never experienced it. Are you running on Linux or Mac ?

**Comment by mameehan5** [comment]
@esclapez I am using Linux on TACC resources primarily. I think there was an update with PelePhysics that required a fresh make of TPL, otherwise I got dramatic slow down in the reaction computation as the simulation progressed (like 100x or more), but I could not clean the original compilation for TPL, so I cloned a fresh version so that TPL was forced to be remade.

**Comment by czc-zju** [comment]
@esclapez I am also using Linux, reinstalling it on a new version.
I'm extremely looking forward to your work on adding diffusion coefficients, thank you in advance.

**Comment by czc-zju** [comment]
@esclapez  Great job!!!  I've got the diffusion coefficient!!!!!!
Greatly Appreciated!!!

**Comment by esclapez** [comment]
@mameehan5 @czc-zju Probably something due to a PelePhysics update, thanks for your feedback.

@czc-zju you probably can switch back to the isoT_EB branch directly now if you want, it's been updated.

I'll close the issue now, I think the initial problem was solved !
